Repository blueprint-site/blueprint-create, pull requests merged in 2025-03, with the labels that each got.

#237 Added cookie dialog animation
  package-lock.json
  package.json
  src/components/features/addons/addon-card/AddonCard.tsx
  src/components/utility/CookieDialog.tsx
Labels: UI/UX, DESIGN

#243 Refactor: Implement blog details page with slug-based routing
  cli/package-lock.json
  src/api/endpoints/useBlogs.tsx
  src/components/features/blog/BlogCard.tsx
  src/components/features/blog/blog-details/BlogDetailsContent.tsx
  src/components/features/blog/blog-details/BlogDetailsFooter.tsx
  src/components/features/blog/blog-details/BlogDetailsHeader.tsx
  src/components/features/blog/blog-details/BlogDetailsMain.tsx
  src/components/features/blog/blog-details/index.ts
  src/pages/blog/BlogDetails.tsx
  src/routes/blogRoutes.tsx
Labels: REFACTOR

#247 Implement dynamic background on About page
  src/api/endpoints/useSearchAddons.tsx
  src/components/features/dynamic-bg/DynamicBg.tsx
  src/components/features/dynamic-bg/index.ts
  src/pages/About.tsx
Labels: UI/UX, DESIGN

#239 Improve Grid Layout & Component Architecture
  package-lock.json
  src/api/endpoints/useBlogs.tsx
  src/api/endpoints/useSearchAddons.tsx
  src/components/features/addons/AddonList.tsx
  src/components/features/addons/addon-card/AddonCard.tsx
  src/components/features/blog/BlogCard.tsx
  src/components/features/schematics/SchematicsList.tsx
  src/components/layout/FiltersContainer.tsx
  src/components/layout/ItemGrid.tsx
  src/components/layout/SearchFilter.tsx
  src/components/layout/SelectFilter.tsx
  src/components/ui/input.tsx
  src/components/ui/select.tsx
  src/components/ui/skeleton.tsx
  src/index.css
  src/layouts/ListPageLayout.tsx
  src/pages/blog/Blog.tsx
  src/schemas/blog.schema.tsx
  src/types/index.ts
Labels: UI/UX, DESIGN

#248 Feat: Fetch blog by ID or slug
  src/api/endpoints/useBlogs.tsx
Labels: HOT-FIX

#249 HOT-FiX: SOME TYPES ERROR
  src/api/endpoints/useSearchAddons.tsx
  src/api/endpoints/useSearchBlogs.tsx
  src/schemas/blog.schema.tsx
  src/types/index.ts
Labels: HOT-FIX

#250 Move file to public folder for hosting purpose
  nginx.conf
  package-lock.json
  public/badges/chat-whit-us-by-email_vector.svg
  public/icons/create_icons.png
  public/icons/create_icons.svg
  public/icons/create_icons_dark.png
  public/icons/discord-mark-black.svg
  public/icons/discord-mark-blue.svg
  public/icons/discord-mark-white.svg
  public/icons/fabric.svg
  public/icons/github-mark-white.svg
  public/icons/github-mark.svg
  public/icons/google-mark-color.png
  src/components/utility/MinecraftIcon.tsx
  src/pages/About.tsx
  test.tsx.tsx
Labels: HOT-FIX

#252 Feat: Implement sidebar component and admin layout
  package-lock.json
  package.json
  src/components/features/admin/addons/AdminAddAddon.tsx
  src/components/features/admin/addons/index.ts
  src/components/layout/AdminPanel/AppSidebar.tsx
  src/components/layout/AdminPanel/NavMain.tsx
  src/components/layout/AdminPanel/NavProjects.tsx
  src/components/layout/AdminPanel/NavUser.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/collapsible.tsx
  src/components/ui/sidebar.tsx
  src/components/utility/ProtectedRoute.tsx
  src/hooks/use-mobile.ts
  src/index.css
  src/layouts/AdminPanelLayout.tsx
  src/pages/Admin.tsx
  src/routes/adminRoutes.tsx
  tsconfig.json
Labels: REFACTOR

#253 Refactor: Improve admin component imports
  src/components/features/admin/AdminLogs/AdminLogsList.tsx
  src/components/features/admin/AdminLogs/index.ts
  src/components/features/admin/addons/AddAddon.tsx
  src/components/features/admin/addons/AddonsTable.tsx
  src/components/features/admin/addons/AdminAddAddon.tsx
  src/components/features/admin/addons/AdminAddonsTable.tsx
  src/components/features/admin/addons/index.ts
  src/components/features/admin/blog/AdminBlogEditor.tsx
  src/components/features/admin/blog/AdminBlogList.tsx
  src/components/features/admin/blog/components/AdminBlogDisplay.tsx
  src/components/features/admin/blog/index.ts
  src/components/features/admin/schematics/AdminSchematicsDisplay.tsx
  src/components/features/admin/schematics/SchematicsDisplay.tsx
  src/components/features/admin/schematics/index.ts
  src/components/features/admin/stats/AddonStatsWrapper.tsx
  src/components/features/admin/stats/index.ts
  src/components/layout/AdminPanel/AppSidebar.tsx
  src/components/tables/blog/AdminBlogTable.tsx
  src/pages/Admin.tsx
  src/pages/index.ts
  src/routes/adminRoutes.tsx
Labels: REFACTOR

#256 feat: Add `@/data` dir for static constants
  src/components/features/schematics/upload/SchematicsUpload.tsx
  src/components/features/schematics/upload/form/MultiSelectCheckboxGroup.tsx
  src/data/createVersions.ts
  src/data/index.ts
  src/data/minecraftIcons.ts
  src/data/minecraftVersions.ts
  src/data/modloaders.ts
  src/data/schematicCategories.ts
Labels: FEATURE, REFACTOR

#257 Easter Egg User Preferences Integration
  src/api/stores/easterEggStore.ts
  src/components/features/home/WhatIsBlueprint.tsx
  src/components/features/settings/DisplaySettings.tsx
  src/components/features/settings/EasterEggSettings.tsx
  src/components/layout/AppFooter.tsx
  src/components/layout/AppHeader.tsx
  src/config/easterEggs.ts
  src/hooks/useEasterEgg.ts
  src/schemas/user.schema.tsx
Labels: FEATURE

#221 Added old logo and an easter egg :eyes:
  src/api/stores/easterEggStore.ts
  src/assets/legacy_logo.webp
  src/components/features/home/WhatIsBlueprint.tsx
  src/components/features/settings/DisplaySettings.tsx
  src/components/features/settings/EasterEggSettings.tsx
  src/components/layout/AppFooter.tsx
  src/components/layout/AppHeader.tsx
  src/config/easterEggs.ts
  src/hooks/useEasterEgg.ts
  src/schemas/user.schema.tsx
Labels: UI/UX, DESIGN

#255 Refactor: Replace LoggedUser Context with Zustand Store for User Management
  src/App.tsx
  src/api/context/loggedUser/loggedUserContext.tsx
  src/api/stores/userStore.ts
  src/components/features/admin/blog/AdminBlogEditor.tsx
  src/components/features/schematics/UserSchematicList.tsx
  src/components/features/schematics/schematic-details/SchematicsDetailsHeader.tsx
  src/components/features/schematics/upload/SchematicsUpload.tsx
  src/components/features/settings/ProfileSettings.tsx
  src/components/layout/AdminPanel/AppSidebar.tsx
  src/components/layout/HeaderNavMenu.tsx
  src/pages/Profile.tsx
  src/pages/auth/Auth.tsx
  src/pages/auth/AuthSuccess.tsx
Labels: REFACTOR

#259 Dependency Cleanup and Package.json Optimization
  package-lock.json
  package.json
Labels: REFACTOR

#262 Add @react/simple-icons for brand icons
  package-lock.json
  package.json
  src/components/features/addons/addon-details/AddonDetailsContent.tsx
Labels: refactor

#263 Small Design Fixes
  src/components/loading-overlays/LoadingOverlay.tsx
  src/layouts/BaseLayout.tsx
Labels: design

#264 Remove Legacy Workflows and Add PR Template
  .github/pull_request_template.md
  .github/workflows/404.md
  .github/workflows/codeql.yml
  .github/workflows/stale.yml
Labels: infrasctucture

#266 Yolo/we need to advance
  src/api/endpoints/useSchematics.tsx
  src/api/endpoints/useSearchSchematics.tsx
  src/api/stores/userStore.ts
  src/components/features/about/ContributorsSection.tsx
  src/components/features/blog/BlogCard.tsx
  src/components/features/blog/blog-details/BlogDetailsFooter.tsx
  src/components/features/blog/blog-details/BlogDetailsMain.tsx
  src/components/features/schematics/UserSchematicList.tsx
  src/components/features/schematics/upload/SchematicUploadForm.tsx
  src/components/features/schematics/upload/SchematicsUpload.tsx
  src/components/features/schematics/upload/form/CategorySelectors.tsx
  src/components/features/schematics/upload/form/MultiSelectCheckboxGroup.tsx
  src/components/features/settings/AccountSettings.tsx
  src/components/layout/HeaderNavMenu.tsx
  src/components/ui/multi-selector.tsx
  src/components/utility/ClientDisplay.tsx
  src/components/utility/OAuthProvidersDisplay.tsx
  src/config/appwrite.ts
  src/data/OAuthProviders.ts
  src/data/modloaders.ts
  src/pages/auth/Auth.tsx
  src/pages/blog/BlogDetails.tsx
  src/routes/blogRoutes.tsx
  src/routes/schematicRoutes.tsx
  src/schemas/OAuthProviders.schema.tsx
  src/schemas/schematic.schema.tsx
  src/types/index.ts
Labels: refactor, in progress

#274 Enhance addon details description rendering
  src/components/features/addons/addon-details/AddonDetailsDescription.tsx
  src/components/features/addons/addon-details/AddonDetailsView.tsx
  src/index.css
Labels: hot-fix

#271 Feat: Add multi-language support
  cli/commands/translate.js
  cli/controller/translate.js
  cli/index.js
  cli/package-lock.json
  cli/package.json
  package-lock.json
  package.json
  public/minecraft-textures/ancient_debris_side.png
  public/minecraft-textures/ancient_debris_top.png
  public/minecraft-textures/bookshelf.png
  public/minecraft-textures/copper_block.png
  public/minecraft-textures/diamond.webp
  public/minecraft-textures/diamond_block.png
  public/minecraft-textures/emerald_block.png
  public/minecraft-textures/gold_block.png
  public/minecraft-textures/lapis_block.png
  public/minecraft-textures/obsidian.png
  public/minecraft-textures/redstone_block.png
  public/minecraft-textures/terracotta.png
  public/minecraft-textures/tnt_side.png
  src/components/features/about/ContactSection.tsx
  src/components/features/about/ContributorsSection.tsx
  src/components/features/about/MissionSection.tsx
  src/components/features/games/tetris/MinecraftTetrisGame.tsx
  src/components/features/home/ForCreators.tsx
  src/components/features/home/UsefulLinks.tsx
  src/components/features/schematics/SchematicsList.tsx
  src/components/features/settings/AccountSettings.tsx
  src/components/features/settings/DisplaySettings.tsx
  src/components/features/settings/EasterEggSettings.tsx
  src/components/features/settings/LanguageSwitcher.tsx
  src/components/features/settings/ProfileSettings.tsx
  src/components/layout/AppFooter.tsx
  src/config/easterEggs.ts
  src/config/i18n.ts
  src/locales/ar.json
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/id.json
  src/locales/index.ts
  src/locales/it.json
  src/locales/ja.json
  src/locales/pl.json
  src/locales/pt.json
  src/locales/ru.json
  src/locales/uk.json
  src/locales/zh.json
  src/pages/About.tsx
  src/pages/NotFound.tsx
  src/pages/Settings.tsx
  src/routes/gamesRoutes.tsx
  src/routes/index.tsx
Labels: feature, infrasctucture

#275 Add Umami analytics script
  index.html
Labels: infrasctucture

#272 Added Addon Verifying proccess
  package-lock.json
  package.json
  src/api/endpoints/useAddons.tsx
  src/assets/eyes/eye_squint.gif
  src/assets/new_create_background.webp
  src/components/features/addons/AddonDetails.tsx
  src/components/features/addons/AddonList.tsx
  src/components/features/addons/addon-card/AddonCard.tsx
  src/components/features/addons/addon-card/AddonStats.tsx
  src/components/features/addons/addon-details/AddonDetailsFooter.tsx
  src/components/features/addons/addon-details/AddonDetailsView.tsx
  src/components/features/settings/AddonVerifyingSettings.tsx
  src/pages/Settings.tsx
  src/schemas/addon.schema.tsx
  src/types/addons/addon-details.ts
Labels: feature, design, in progress

#278 Fix: Improve schematic edit form and list
  package-lock.json
  src/components/common/VersionsDisplay.tsx
  src/components/features/addons/addon-card/ModLoaders.tsx
  src/components/features/schematics/UserSchematicList.tsx
  src/components/features/schematics/schematic-details/SchematicsDetailsContent.tsx
  src/components/features/schematics/upload/SchematicUploadForm.tsx
  src/components/features/schematics/upload/form/FileUploadField.tsx
  src/index.css
  src/pages/NotFound.tsx
Labels: feature

#279 Feature/addon verification
  .eslintignore
  .eslintrc.cjs
  eslint.config.mjs
  package-lock.json
  package.json
  src/api/endpoints/useAddons.tsx
  src/api/endpoints/useModrinth.tsx
  src/api/index.tsx
  src/components/features/addons/AddonDetails.tsx
  src/components/features/addons/AddonList.tsx
  src/components/features/addons/addon-card/AddonCard.tsx
  src/components/features/addons/addon-card/AddonStats.tsx
  src/components/features/addons/addon-card/ModLoaders.tsx
  src/components/features/addons/addon-details/AddonDetailsFooter.tsx
  src/components/features/addons/addon-details/AddonDetailsView.tsx
  src/components/features/admin/addons/AddonsTable.tsx
  src/components/features/settings/addon-verification/AddonVerification.tsx
  src/components/features/settings/addon-verification/AddonVerificationDialog.tsx
  src/components/features/settings/addon-verification/components/AddonFetcher.tsx
  src/components/features/settings/addon-verification/components/TimerProgress.tsx
  src/components/features/settings/addon-verification/index.tsx
  src/components/features/settings/addon-verification/steps/ClaimAddonsStep.tsx
  src/components/features/settings/addon-verification/steps/ConfirmationStep.tsx
  src/components/features/settings/addon-verification/steps/CurseForgeStep.tsx
  src/components/features/settings/addon-verification/steps/ModrinthAuthStep.tsx
  src/components/features/settings/addon-verification/steps/ModrinthProfileStep.tsx
  src/components/features/settings/addon-verification/steps/ModrinthValidationStep.tsx
  src/components/features/settings/addon-verification/steps/PlatformSelectionStep.tsx
  src/components/features/settings/addon-verification/types.ts
  src/pages/Settings.tsx
  src/schemas/addon.schema.tsx
  src/types/addons/modrinth.ts
  src/types/index.ts
Labels: feature, refactor, design

#280 Implement toolbox with upload, addons and profile links
  package-lock.json
  package.json
  src/components/common/Cogwheel.tsx
  src/components/layout/ToolsBox.tsx
  src/components/ui/drawer.tsx
  src/index.css
Labels: feature

#287 docs: Improve contributing documentation and standardize GitHub workflow
  .github/ISSUE_TEMPLATE/01-hotfix.yml
  .github/ISSUE_TEMPLATE/02-bug.yml
  .github/ISSUE_TEMPLATE/03-feature.yml
  .github/ISSUE_TEMPLATE/04-documentation.yml
  .github/ISSUE_TEMPLATE/05-design.yml
  .github/ISSUE_TEMPLATE/06-infrastructure.yml
  .github/ISSUE_TEMPLATE/07-refactor.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
  README.md
  docs/contributing/code-standards.md
  docs/contributing/getting-started.md
  docs/contributing/index.md
  docs/contributing/issue-guidelines.md
  docs/contributing/workflow.md
Labels: priority: low
